config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :customer do
    resources:addresses, only: [:index, :create, :destroy, :edit, :update]
    resources:orders, only: [:index, :new, :create, :show]do
      collection do
        post :check
        get :thanks
      end
    end
    resources:cart_items, only: [:index, :create, :destroy, :update]do
      collection do
       delete "destroy_all"
      end
     end
    resources:items, only: [:index, :show]
    resources:customers, only: [:show, :edit, :update]do
      collection do
        get :quit
        patch :out
      end
    end
    get 'homes/top' => "homes#top"
    get 'homes/about' => "homes#about"
    root to: 'homes#top'
  end
  namespace :admin do
    root "orders#index"
    resources:orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources:genres, only: [:index, :create, :edit, :update]
    resources:items, only: [:index, :new, :show, :create, :edit, :update]
    resources:customers, only: [:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true}
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
	end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:telephone_number,:email,:is_active)
	end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  
  def index
    @addresses = Address.all
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.address
    if @address.save
      flash.now[:notice] = "新規配送先を登録しました"
	    redirect_to addresses_path
    else
	    render 'index'
    end
  end

  def destroy
    @address = Address.find(params[:id])
	  @address.destroy
    flash.now[:alert] = "配送先を削除しました"
	  redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
	  if @address.update(address_params)
  	 flash[:success] = "配送先を変更しました"
     redirect_to addresses_path
	  else
	   render "edit"
	  end
  end
  
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items.all
    @customer_cart_items = CartItem.where(customer_id: current_customer.id)
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(params_cart_item)
    redirect_to cart_items_path, notice: "個数の変更が完了しました"
  end

  def create
    @cart_item = current_customer.cart_items.new(params_cart_item)
    @item = @cart_item.item

      # カートの中に同じ商品が重複しないようにして　古い商品と新しい商品の数量を合わせる
    @update_cart_item =  CartItem.find_by(item_id: @cart_item.item.id)
    if @update_cart_item.present?
      @cart_item.amount += @update_cart_item.amount
      @update_cart_item.destroy
    end
    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました"
      redirect_to cart_items_path
    else
      redirect_to item_path(@item), notice: "商品の個数を指定してください"
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path, notice: "#{@cart_item.item.name}を削除しました"
  end


  def destroy_all
    if CartItem.destroy_all
      redirect_to cart_items_path, notice: "カート内を全て削除しました"
    end
  end

  private

  def params_cart_item
    params.require(:cart_item).permit(:customer_id, :amount, :item_id)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_active: false)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def edit
     @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customer_path
    else
       render :edit
    end

  end

  private

    def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
    end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @items = Item.all.order(created_at: :desc)
    #=> :asc,古い順 :desc,新しい順　
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
    @items_all = Item.all

    #if
      #@items_all = Item.where(is_active: true)
      # ジャンルが有効かつ商品も販売中の商品のみ表示させる
      #@items = @item_all#.page(params[:page]).reverse_order
    #else
      #@item_all = Item.joins(:genre).where(genres: { is_active: true, id: params[:genre_id] }).where(is_active: true)
      #@items = @item_all.page(params[:page]).reverse_order
      #@index = Genre.find( params[:genre_id]).name
    #end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end


  private
    def item_params
		parmas.require(:item).permit(:image ,:name, :introduction, :price, :is_active, :genre_id)
	  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def check
    @order = Order.new(order_params) #受け取った注文情報
    @order.customer_id = current_customer.id #注文情報に自分のIDを入れる
    @order.postage = 800 #送料を設定する
    @cart_items = current_customer.cart_items #自分のカート内商品を取り出す
    #@total_payment = @order.postage + @cart_items.sum_of_price #請求額の合計を割り出す
    @sum = 0
    @subtotals = @cart_items.map { |cart_item| (Item.find(cart_item.item_id).price * 1.1 * cart_item.amount).to_i }
    @sum = @subtotals.sum

    if params[:order][:addresses] == "0" #お届けの方法が自分の住所の時
      @name = current_customer.first_name + current_customer.last_name
      @postal_code = current_customer.postal_code
      @address = current_customer.address
    elsif params[:order][:addresses] == "1" #お届けの方法が登録している住所の時
      @customer_address = Address.find(params[:order][:address_id])
      @name = @customer_address.name
      @postal_code = @customer_address.postal_code
      @address = @customer_address.address
    elsif  params[:order][:addresses] == "2" #新しいお届け先
      @name = @order.name
      @postal_code = @order.postal_code
      @address = @order.address
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      @cart_items = current_customer.cart_items.all
      @cart_items.each do |cart_item|
        @order_details = @order.order_details.new
        @order_details.item_id = cart_item.item.id
        @order_details.price = cart_item.item.price * 1.1
        @order_details.amount = cart_item.amount
        @order_details.save
        current_customer.cart_items.destroy_all
      end
      redirect_to thanks_orders_path
    else
      @addresses = current_customer.addresses
      render :new
    end
  end

  def thanks
  end

  def index
    @orders = Order.where(customer_id: current_customer.id).page(params[:page]).per(5)
  end

  def show
    @order = Order.find(params[:id])
    @sum = 0
    @subtotals = @order.order_details.map { |order_detail| (Item.find(order_detail.item_id).price * 1.1 * order_detail.amount).to_i }
    @sum = @subtotals.sum
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postage, :total_payment, :payment_method, :name, :postal_code, :address, :order_status)
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  #before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/adresses_helper.rb
module Customer::AdressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/customers/edit.html.erb
<div class="container style=font-family: 'Noto Sans JP',serif; margin: 150px;">
  <div cass="text-center">
   <br>
   <h2>会員情報編集</h2>
    <br>
     <div class="actions">
    <%= form_with model:@customer, local:true do |f| %>
    <div>
    <div class="form-group">
     <%= f.label "氏名",class: "col-sm-2 control-label mr-5"%>
    <%= f.text_field :first_name, class: "col-sm-3 control-label" %><%= f.text_field :last_name, class: "col-sm-3 control-label" %>
    </div>

    <div class="form-group">
    <%= f.label "カナ",class: "col-sm-2 control-label mr-5"%>
    <%= f.text_field :first_name_kana, class: "col-sm-3 control-label" %><%= f.text_field :last_name_kana, class: "col-sm-3 control-label" %>
    </div>

    <div class="form-group">
     <%= f.label " 郵便番号",class: "col-sm-2 control-label mr-5" %>
     <%= f.text_field :postal_code, class: "col-sm-3 control-label" %>
    </div>

    <div class="form-group">
    <%= f.label " 住所",class: "col-sm-2 control-label mr-5" %>
    <%= f.text_field :address, class: "col-sm-6 control-label" %>
    </div>

    <div class="form-group">
    <%= f.label " 電話番号",class: "col-sm-2 control-label mr-5" %>
    <%= f.text_field :telephone_number, class: "col-sm-3 control-label" %>
    </div>

    <div class="form-group">
      <%= f.label " メールアドレス",class: "col-sm-2 control-label mr-5" %>
    <%= f.text_field :email, class: "col-sm-3 control-label" %>
    </div>

    <%= f.submit "編集内容を保存する", class: "btn mt-2", style: "background-color: #cbb05e; color: black;" %>
    <%= link_to '退会する', quit_customers_path, class: "glyphicon glyphicon-tint btn btn-danger mt-2"%>
    <% end %>
    </div>
   </div>
  </div>
</div>

app/views/customer/customers/quit.html.erb
<div class="container text-center">
<% provide(:title, "退会ページ") %>
　<div class="quit">
  <strong>本当に退会しますか？</strong>
    <div class="quit-msg">
      退会すると会員情報登録や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      <br>
      退会する場合は,「退会する」をクリックしてください。
    </div>

  <div>
    <%= link_to "退会しない", customer_path(@customer) %>
    <%= link_to "退会する", out_customers_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>
  </div>
</div>
</div>

app/views/customer/customers/show.html.erb
<div class="container" style="font-family: 'Noto Sans JP',serif; margin-top: 25px;">
 <table class="table table-bordered">
  <thead>
   <br>
    <h1>マイページ</h1>
   <br>
    <strong>登録情報</strong> &emsp;  <%= link_to "編集する",edit_customer_path(@customer),  class: "btn", style: "background-color: #cbb05e; color: black;"%>
   <br>
    <colgroup>
      <col class="col-sm-2 control-label mr-4 ">
      <col class="col-mr-4">
    </colgroup>
    <tbody>
      <tr>
       <th>氏名</th>
        <td><%= @customer.first_name %> <%= @customer.last_name %></td>
      </tr>

      <tr>
        <th>カナ</th>
        <td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
      </tr>

      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>

      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>

      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
     </tbody>
  </tabele>
  <br>
    <table class="adresses">
  	 <p><strong>配送先</strong> &emsp;&emsp;  <%= link_to "一覧を見る",addresses_path, class: "btn mt-3", style: "background-color: #6599cc; color: white;"%></p>
  	</table>
  	<table class="orders">
  		<p><strong>注文履歴</strong> &emsp; <%= link_to "一覧を見る",orders_path, class: "btn mt-3", style: "background-color: #6599cc; color: white;" %></p>
  	</table>
</div>