config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :customer do
    resources:addresses, only: [:index, :create, :destroy, :edit, :update]
    resources:orders, only: [:index, :new, :create, :show]do
      collection do
        post :check
        get :thanks
      end
    end
    resources:cart_items, only: [:index, :create, :destroy, :update]do
      collection do
       delete "destroy_all"
      end
     end
    resources:items, only: [:index, :show]
    resources:customers, only: [:show, :edit, :update]do
      collection do
        get :quit
        patch :out
      end
    end
    get 'homes/top' => "homes#top"
    get 'homes/about' => "homes#about"
    root to: 'homes#top'
  end
  namespace :admin do
    root "orders#index"
    resources:orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources:genres, only: [:index, :create, :edit, :update]
    resources:items, only: [:index, :new, :show, :create, :edit, :update]
    resources:customers, only: [:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  has_many :orders, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\u{30fc}]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, numericality: {only_integer: true}
  validates :email, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  
  #0は入金待ち（デフォルト）、１は入金確認、２は製作中、３は発送準備中、４は発送済み
  enum order_status: { waiting_payment: 0, payment_confirm: 1, in_production: 2, ready_to_ship: 3, shipped: 4 }
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
	end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:telephone_number,:email,:is_active)
	end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    # 下記３行は商品合計を出すため
    @sum = 0
    @subtotals = @order_details.map { |order_detail| order_detail.price * order_detail.amount }
    @sum = @subtotals.sum
  end

  def update
   #注文ステータスの更新
      @order = Order.find(params[:id])
      @order.update(order_params)
      if @order.payment_confirm? #enumの確認メソッド
        @order.order_details.each do |order_detail|
        order_detail.waiting_production! #enumの更新メソッド
      end
  end
      redirect_to admin_order_path
end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  
  def index
    @addresses = Address.all
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.address
    if @address.save
      flash.now[:notice] = "新規配送先を登録しました"
	    redirect_to addresses_path
    else
	    render 'index'
    end
  end

  def destroy
    @address = Address.find(params[:id])
	  @address.destroy
    flash.now[:alert] = "配送先を削除しました"
	  redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
	  if @address.update(address_params)
  	 flash[:success] = "配送先を変更しました"
     redirect_to addresses_path
	  else
	   render "edit"
	  end
  end
  
  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items = current_customer.cart_items.all
    @customer_cart_items = CartItem.where(customer_id: current_customer.id)
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(params_cart_item)
    redirect_to cart_items_path, notice: "個数の変更が完了しました"
  end

  def create
    @cart_item = current_customer.cart_items.new(params_cart_item)
    @item = @cart_item.item

      # カートの中に同じ商品が重複しないようにして　古い商品と新しい商品の数量を合わせる
    @update_cart_item =  CartItem.find_by(item_id: @cart_item.item.id)
    if @update_cart_item.present?
      @cart_item.amount += @update_cart_item.amount
      @update_cart_item.destroy
    end
    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました"
      redirect_to cart_items_path
    else
      redirect_to item_path(@item), notice: "商品の個数を指定してください"
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path, notice: "#{@cart_item.item.name}を削除しました"
  end


  def destroy_all
    if CartItem.destroy_all
      redirect_to cart_items_path, notice: "カート内を全て削除しました"
    end
  end

  private

  def params_cart_item
    params.require(:cart_item).permit(:customer_id, :amount, :item_id)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_active: false)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def edit
     @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customer_path
    else
       render :edit
    end

  end

  private

    def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
    end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
    @items = Item.all.order(created_at: :desc)
    #=> :asc,古い順 :desc,新しい順　
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
    @items_all = Item.all

    #if
      #@items_all = Item.where(is_active: true)
      # ジャンルが有効かつ商品も販売中の商品のみ表示させる
      #@items = @item_all#.page(params[:page]).reverse_order
    #else
      #@item_all = Item.joins(:genre).where(genres: { is_active: true, id: params[:genre_id] }).where(is_active: true)
      #@items = @item_all.page(params[:page]).reverse_order
      #@index = Genre.find( params[:genre_id]).name
    #end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end


  private
    def item_params
		parmas.require(:item).permit(:image ,:name, :introduction, :price, :is_active, :genre_id)
	  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def new
    @order = Order.new
    @addresses = current_customer.addresses
  end

  def check
    @order = Order.new(order_params) #受け取った注文情報
    @order.customer_id = current_customer.id #注文情報に自分のIDを入れる
    @order.postage = 800 #送料を設定する
    @cart_items = current_customer.cart_items #自分のカート内商品を取り出す
    #@total_payment = @order.postage + @cart_items.sum_of_price #請求額の合計を割り出す
    @sum = 0
    @subtotals = @cart_items.map { |cart_item| (Item.find(cart_item.item_id).price * 1.1 * cart_item.amount).to_i }
    @sum = @subtotals.sum

    if params[:order][:addresses] == "0" #お届けの方法が自分の住所の時
      @name = current_customer.first_name + current_customer.last_name
      @postal_code = current_customer.postal_code
      @address = current_customer.address
    elsif params[:order][:addresses] == "1" #お届けの方法が登録している住所の時
      @customer_address = Address.find(params[:order][:address_id])
      @name = @customer_address.name
      @postal_code = @customer_address.postal_code
      @address = @customer_address.address
    elsif  params[:order][:addresses] == "2" #新しいお届け先
      @name = @order.name
      @postal_code = @order.postal_code
      @address = @order.address
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      @cart_items = current_customer.cart_items.all
      @cart_items.each do |cart_item|
        @order_details = @order.order_details.new
        @order_details.item_id = cart_item.item.id
        @order_details.price = cart_item.item.price * 1.1
        @order_details.amount = cart_item.amount
        @order_details.save
        current_customer.cart_items.destroy_all
      end
      redirect_to thanks_orders_path
    else
      @addresses = current_customer.addresses
      render :new
    end
  end

  def thanks
  end

  def index
    @orders = Order.where(customer_id: current_customer.id).page(params[:page]).per(5)
  end

  def show
    @order = Order.find(params[:id])
    @sum = 0
    @subtotals = @order.order_details.map { |order_detail| (Item.find(order_detail.item_id).price * 1.1 * order_detail.amount).to_i }
    @sum = @subtotals.sum
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postage, :total_payment, :payment_method, :name, :postal_code, :address, :order_status)
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  #before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/adresses_helper.rb
module Customer::AdressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/customer/orders/check.html.erb
<div class="container taksa" style="font-family: 'Noto Sans JP',serif; margin-top: 50px;">
  <div class="row">
    <div class="col">

      <h2>注文情報確認</h2>
      <% @sum = 0 %>

      <div class="row mt-3">
      <div class="col-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to item_path(cart_item) do %>
                <%=  attachment_image_tag cart_item.item, :image, size: "200x150", fallback: "no_image.jpg" %><br>
                <%= cart_item.item.name %>
              <% end %>
            </td>
            <td>
              <% @item_price = cart_item.item.price * 1.1 %>
              ¥<%= @item_price.floor.to_s(:delimited) %>
            </td>
            <td>
              <%= cart_item.amount %>
            </td>
            <td>
              <% @total_price = @item_price * cart_item.amount %>
              ¥<%= @total_price.floor.to_s(:delimited) %>
            </td>
          </tr>
          <% @sum += @total_price %>
          <% end %>
        </tbody>
      </table>
      </div>

      <div class="col-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>送料</th>
            <td><%= @order.postage %></td>
          </tr>
          <tr>
            <th>商品合計</th>
            <td><%= @sum.floor.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td><%= (@sum.floor + @order.postage).to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
      </div>
      </div>

      <div class="row">
        <h3 class="mr-3">支払い方法</h3>
        <p style="font-size: 20px;"><%= @order.payment_method_i18n %></p>
      </div>
      <div class="row">
        <h3 class="mr-3">お届け先</h3>
        〒<p style="font-size: 20px;"><%= @postal_code %></p>　<p style="font-size: 20px;"><%= @address %></p>　<p style="font-size: 20px;"><%= @name %></p>
      </div>

      <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :payment_method, value: @order.payment_method %>
        <%= f.hidden_field :customer_id, value: current_customer.id %>
        <%= f.hidden_field :postage, value: 800 %>
        <%#= f.hidden_field :total_payment, value: @total_payment %>
        <%= f.hidden_field :name, value: @name %>
        <%= f.hidden_field :address, value: @address %>
        <%= f.hidden_field :postal_code, value: @postal_code %>
        <!--<=% if params[:order][:delivery_address] == "0" %>-->
        <!--  <=%= f.hidden_field :shipping_name, value: current_customer.last_name + current_customer.first_name %>-->
        <!--  <=%= f.hidden_field :shipping_address, value: current_customer.address %>-->
        <!--  <=%= f.hidden_field :shipping_post_cord, value: current_customer.post_cord %>-->
        <!--<=% elsif params[:order][:delivery_address] == "1" %>-->
        <!--  <=%= f.hidden_field :shipping_name, value: @customer_address.pluck(:name) %>-->
        <!--  <=%= f.hidden_field :shipping_address, value: @customer_address.pluck(:address) %>-->
        <!--  <=%= f.hidden_field :shipping_post_cord, value: @customer_address.pluck(:post_cord) %>-->
        <!--<=% elsif params[:order][:delivery_address] == "2" %>-->
        <!--  <=%= f.hidden_field :shipping_name, value: @order.shipping_name %>-->
        <!--  <=%= f.hidden_field :shipping_address, value: @order.shipping_address %>-->
        <!--  <=%= f.hidden_field :shipping_post_cord, value: @order.shipping_post_cord %>-->
        <!--<=% end %>-->
        <div class="text-center mt-5">
        <%= f.submit "注文を確定する", class: "btn" ,style: "background-color: #cbb05e; color: black;" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/customer/orders/create.html.erb
<h1>Customer::Orders#create</h1>
<p>Find me in app/views/customer/orders/create.html.erb</p>

app/views/customer/orders/index.html.erb
<div class="container " style="font-family: 'Noto Sans JP',serif; margin-top: 50px;">

  <div class="row">
      <h3>注文履歴一覧</h3>
  </div>

<% if @orders.exists? %>
  <div class="row mt-5">
    <table class="table table-bordered table-hover">

      <thead class="table-active text">
        <tr>
          <th>注文日</th>
          <th>配送先</th>
          <th>注文商品</th>
          <th>支払金額</th>
          <th>ステータス</th>
          <th>注文詳細</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
        <% @sum = 0 %>
        <tr class="light-text">
          <td><%= order.created_at.strftime('%Y年%m月%d日') %></td>
          <td>
              〒<%= order.postal_code %><br>
              <%= order.address %><br>
              <%= order.name %> 様
          </td>
          <td>
            <% order.order_details.each do |f| %>
            <% @sum += f.price * f.amount %>
              <%= f.item.name %><br>
            <% end %>
          <td>¥<%= (@sum.floor + order.postage).to_s(:delimited) %></td>
          <td><%= order.order_status_i18n %></td>
          <td>
            <%= link_to "詳細", order_path(order.id), class: "btn", style: "background-color: #cbb05e; color: black;" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination"><%= paginate @orders %></div>
  </div>



  <% else %>
      <div class="text-center">
        <h2>※注文履歴がありません</h2>
      </div>
  <% end %>
</div>

app/views/customer/orders/new.html.erb
<div class="container taksa" style="font-family: 'Noto Sans JP',serif; margin-bottom: 250px;">
  <div class="row">
    <div class="col">
      <div class="validates mb-5">
        <% if @order.errors.any? %>
            -<%= @order.errors.count %>箇所の入力漏れがあります-
            <% @order.errors.full_messages.each do |message| %><br>
            ・<%= message %>
            <% end %>
        <% end %>
      </div>
      <h2>注文情報入力</h2>
      <%= form_with model: @order,url: check_orders_path, method: :post, local: true do |f| %>
      <div class="mt-5">
        <p>支払い方法</p>
        <%= f.radio_button :payment_method, "credit_card" %>
        <%= f.label :payment_method, "クレジットカード" %>

        <%= f.radio_button :payment_method, "transfer" %>
        <%= f.label :payment_method, "銀行振込" %>
      </div>

      <div class="mt-3">
        <p>お届け先</p>
      </div>
      <div>
        <%= f.radio_button :addresses, 0, checked: true %>
        <%= f.label :addresses, "ご自身の住所", value: 0,class: "col-sm-3 control-label"%>
        〒<%= current_customer.postal_code %>　<%= current_customer.address %>
        <%= current_customer.first_name %><%= current_customer.last_name %>
      </div>
      <div>
        <%= f.radio_button :addresses, 1 %>
        <%= f.label :addresses, "登録済住所から選択", value: 1,class: "col-sm-3 control-label" %>
        <%= f.collection_select :address_id, @addresses, :id, :address , :prompt => "選択してください" %>
      </div>
      <div>
        <%= f.radio_button :addresses, 2 %>
        <%= f.label :addresses, "新しいお届け先", value: 2 %>
      </div>
      <div>
        <%= f.label :new_address, "郵便番号（ハイフンなし）",class: "col-sm-3 control-label"%>
        <%= f.text_field :postal_code, :placeholder => "0000000" %>
      </div>
      <div>
        <%= f.label :new_address, "住所",class: "col-sm-3 control-label"%>
        <%= f.text_field :address, :placeholder => "東京都渋谷区代々木神園町０−０", :size =>"38x10"%>
      </div>
      <div>
        <%= f.label :new_address, "宛名",class: "col-sm-3 control-label"%>
        <%= f.text_field :name, :placeholder => "令和道子" %>
      </div>
      <div>
        <%= f.submit "確認画面に進む", class: "btn mt-5", style: "background-color: #cbb05e; color: black;" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container " style="font-family: 'Noto Sans JP',serif; margin-top: 50px;">
<div class="row">
  <h3>注文履歴詳細</h3>
</div>

<div class="row">
  <div class="col-md-6 pt-3">
    <h4>注文情報</h4>
    <table class="table table-light table-borderless border">
      <tbody>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postal_code %><br>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <td><%= @order.order_status_i18n %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="col-md-4 pt-3">
    <h4>請求情報</h4>
    <table class="table table-light table-borderless border">
      <tbody>
       <tr>
        <th>商品合計</th>
          <td>¥<%= @sum.floor.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td>¥<%= @order.postage.to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>ご請求額</th>
          <td>¥<%= (@sum.floor + @order.postage).to_s(:delimited) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-8 pt-3">
    <h4>注文内容</h4>
    <table class="table table-light table-borderless border">
      <thead>
        <tr>
          <th>商品</th>
          <th>単価(税込)</th>
          <th>個数</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td>¥<%= (order_detail.price * order_detail.amount).floor.to_s(:delimited) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/customer/orders/thanks.html.erb
<div class="container">
 <div class="row">
  <div class="col-12" style="position: relative; display:inline-block;">
    <%= image_tag 'cupcake-279523_1280.jpg', class: "img-fluid" %>
    <div class="col-12" style="position: absolute;top: 50px; text-align: center; ">
      <h4>
       <div class="font-family: 'Noto Sans JP', sans-serif;">
        <p class="h5">
        ご注文ありがとうございました。<br>
        またのお買い上げ、お待ちしております。
        </p>
       </div>
      </h4>
     </div>
    </div>
 </div>
</div>